### ISSUE TITLE
Implement system for using pinning file suport on the resolver

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

After this [Ayon_Usd_Resolver_Pinning_File_Suport]() is implemented, we need to build a mechanism to set needed information and utilise the feature

### How would you imagine the implementation of the feature?

It would need to be a function or set of functions that will set the correct env variables before startup. (could be in the pre-startup hock) 
this system needs to be aware of what type of system it is running and if it should be enabled. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

## TODO

- [x] implement a function to generate a pinning file 
- [x] implement a function to write a pinning file 
- [ ] implement a startup system to load the resolver with the pinning file

**Comment by Lypsolon** [comment]
moved and split into separate issues
